# Generated by Django 4.0.4 on 2022-05-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0003_menu_tel_for_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='tel_for_call',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
