# Generated by Django 4.0.4 on 2022-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0004_alter_menu_tel_for_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselhead',
            name='file',
        ),
        migrations.AddField(
            model_name='carouselhead',
            name='general_img',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselhead',
            name='img',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
    ]
