# Generated by Django 4.0.4 on 2022-05-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0005_remove_carouselhead_file_carouselhead_general_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselhead',
            name='img',
        ),
        migrations.AddField(
            model_name='carouselhead',
            name='img_1',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselhead',
            name='img_2',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselhead',
            name='img_3',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselhead',
            name='img_4',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselhead',
            name='img_5',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselhead',
            name='img_6',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselhead',
            name='img_7',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
    ]
