# Generated by Django 4.0.4 on 2022-05-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0006_remove_carouselhead_img_carouselhead_img_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselhead',
            name='img_3',
        ),
        migrations.RemoveField(
            model_name='carouselhead',
            name='img_4',
        ),
        migrations.RemoveField(
            model_name='carouselhead',
            name='img_5',
        ),
        migrations.RemoveField(
            model_name='carouselhead',
            name='img_6',
        ),
        migrations.RemoveField(
            model_name='carouselhead',
            name='img_7',
        ),
    ]
