# Generated by Django 4.0.4 on 2022-05-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0007_remove_carouselhead_img_3_remove_carouselhead_img_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselhead',
            name='name',
            field=models.CharField(default='редактировать_главную_карусель', max_length=30),
        ),
    ]
