# Generated by Django 4.0.4 on 2022-05-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0008_alter_carouselhead_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouseltrainer',
            name='file',
        ),
        migrations.AddField(
            model_name='carouseltrainer',
            name='general_img',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouseltrainer',
            name='img_1',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouseltrainer',
            name='img_2',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carouseltrainer',
            name='name',
            field=models.CharField(default='редактировать_тренер_карусель', max_length=30),
        ),
    ]
