# Generated by Django 4.0.4 on 2022-05-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0009_remove_carouseltrainer_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='files/')),
            ],
        ),
    ]
