# Generated by Django 4.0.4 on 2022-05-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0011_titleshortcuticon'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title_1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_4',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_5',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
