# Generated by Django 4.0.4 on 2022-05-23 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0015_remove_menu_age_agecard_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouseltrainer',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_site.menu'),
            preserve_default=False,
        ),
    ]
