# Generated by Django 4.0.4 on 2022-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0019_remove_carouseltrainer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('for_script', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='carouselhead',
            name='general_img',
            field=models.FileField(upload_to='files/', verbose_name='первая картинка в слайдере'),
        ),
    ]
