# Generated by Django 4.0.4 on 2022-05-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0020_contacts_alter_carouselhead_general_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_site.menu'),
            preserve_default=False,
        ),
    ]
