# Generated by Django 4.0.4 on 2022-05-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0022_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
