# Generated by Django 4.0.4 on 2022-05-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0026_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='tel',
            field=models.CharField(max_length=30),
        ),
    ]
