# Generated by Django 4.0.4 on 2022-05-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0027_alter_feedback_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.TextField(),
        ),
    ]
