# Generated by Django 4.0.4 on 2022-05-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0028_alter_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agecard',
            name='description',
            field=models.CharField(max_length=100, verbose_name='описание карточки'),
        ),
        migrations.AlterField(
            model_name='agecard',
            name='img',
            field=models.FileField(upload_to='files/', verbose_name='картинка карточки'),
        ),
        migrations.AlterField(
            model_name='carouselhead',
            name='img_1',
            field=models.FileField(upload_to='files/', verbose_name='вторая картинка в слайдере'),
        ),
        migrations.AlterField(
            model_name='carouselhead',
            name='img_2',
            field=models.FileField(upload_to='files/', verbose_name='третья картинка в слайдере'),
        ),
        migrations.AlterField(
            model_name='carouseltrainer',
            name='general_img',
            field=models.FileField(upload_to='files/', verbose_name='первая картинка в слайдере'),
        ),
        migrations.AlterField(
            model_name='carouseltrainer',
            name='img_1',
            field=models.FileField(upload_to='files/', verbose_name='вторая картинка в слайдере'),
        ),
        migrations.AlterField(
            model_name='carouseltrainer',
            name='img_2',
            field=models.FileField(upload_to='files/', verbose_name='третья картинка в слайдере'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='adress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='description',
            field=models.TextField(verbose_name='описание как добраться'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='for_script',
            field=models.TextField(verbose_name='скрипт для отображения карты, копируем только ссылку https... из яндекс конструктор карт'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='название сайта в шапке'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='btn_name_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='надпись на кнопке в блоке'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='btn_name_4',
            field=models.CharField(blank=True, max_length=100, verbose_name='надпись на кнопке в блоке'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='btn_name_menu',
            field=models.CharField(blank=True, max_length=100, verbose_name='надпись на кнопке в шапке'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='footer',
            field=models.TextField(verbose_name='текст футер'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='имя ссылки в меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='имя ссылки в меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='имя ссылки в меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_4',
            field=models.CharField(blank=True, max_length=100, verbose_name='имя ссылки в меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_5',
            field=models.CharField(blank=True, max_length=100, verbose_name='имя ссылки в меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tel',
            field=models.CharField(max_length=100, verbose_name='поле для телефонного номера, вводить в красивом формате, пример:+7 (955) 893-23-22'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='text_1',
            field=models.TextField(verbose_name='текст блока'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='text_3',
            field=models.TextField(verbose_name='текст блока'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='text_4',
            field=models.TextField(verbose_name='текст блока'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок блока'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок блока'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок блока'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_4',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок блока'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_5',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок блока'),
        ),
        migrations.AlterField(
            model_name='titleshortcuticon',
            name='img',
            field=models.FileField(upload_to='files/', verbose_name='картинка на вкладке'),
        ),
        migrations.AlterField(
            model_name='titleshortcuticon',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название сайта (надпись на вкладке)'),
        ),
    ]
