# Generated by Django 4.0.4 on 2022-05-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0029_alter_agecard_description_alter_agecard_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='social_data_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='ссылка на соц.сеть'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='social_data_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='ссылка на соц.сеть'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='social_img_1',
            field=models.FileField(upload_to='files/', verbose_name='иконка соц.сети'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='social_img_2',
            field=models.FileField(upload_to='files/', verbose_name='иконка соц.сети'),
        ),
    ]
