# Generated by Django 4.0.4 on 2022-07-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0031_alter_feedback_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='text_3',
            new_name='a_faq',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='item_2',
            new_name='item_club',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='item_3',
            new_name='item_contacts',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='item_4',
            new_name='item_faq',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='text_4',
            new_name='q_faq',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title_2',
            new_name='title_club',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title_3',
            new_name='title_contacts',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title_4',
            new_name='title_faq',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='btn_name_4',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='item_5',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='title_5',
        ),
        migrations.AddField(
            model_name='menu',
            name='text_club',
            field=models.TextField(default=1, verbose_name='текст блока'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AgeCard',
        ),
    ]
