# Generated by Django 4.0.4 on 2022-07-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0035_remove_clubfoto_foto_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=255, verbose_name='название филиала')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_site.menu')),
            ],
        ),
    ]
