# Generated by Django 4.0.4 on 2022-07-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0036_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='adr',
            field=models.CharField(default=1, max_length=255, verbose_name='адрес филиала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filial',
            name='way',
            field=models.CharField(default=1, max_length=255, verbose_name='как добраться до филиала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='a_faq',
            field=models.CharField(max_length=255, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='q_faq',
            field=models.CharField(max_length=255, verbose_name='вопрос'),
        ),
    ]
